name = "temzone"
main = "dist/index.mjs"
compatibility_date = "2023-01-20"

[site]
bucket = "assets"

[build]
command = "node esbuild.config.js"
watch_dir = "src"

[env.dev]
d1_databases = [
  { binding = "DB", database_name = "temzone", database_id = "e97c4ba8-9e00-46e9-ba95-2c52b2f0dcf7" }
]
kv_namespaces = [
  { binding = "CACHE", id = "7a20f210408e4a7dae7e76976723b81a", preview_id = "7a20f210408e4a7dae7e76976723b81a" }
]

[env.prod]
d1_databases = [
  { binding = "DB", database_name = "temzone", database_id = "6a0aa86b-d3dc-4171-889d-dc0fc3ae75c7" }
]
kv_namespaces = [
  { binding = "CACHE", id = "86b34f4cba3e4adb98e2d850012f5dda" }
]
