name: CI/CD
on:
  push:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-22.04
    name: Deploying
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: npm
      - name: Deploy to production
        uses: cloudflare/wrangler-action@2.0.0
        if: github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: npm install
          command: publish --env prod
          postCommands: echo y | wrangler d1 migrations apply temzone --env prod
          secrets: |
            FIREBASE_PROJECT_ID
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Deploy to develop
        uses: cloudflare/wrangler-action@2.0.0
        if: github.ref == 'refs/heads/develop'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: npm install
          command: publish --env dev
          postCommands: echo y | wrangler d1 migrations apply temzone --env dev
          secrets: |
            FIREBASE_PROJECT_ID
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
