name: CI/CD
on:
  push:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-22.04
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    name: Deploying
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Set environment variables
        run: echo "${{ secrets.FIREBASE_PROJECT_ID }}" | eval "npx wrangler secret put FIREBASE_PROJECT_ID --env ${{ secrets.ENVIRONMENT }}"
      - name: Migrate database
        run: echo y | eval "npx wrangler d1 migrations apply temzone --env ${{ secrets.ENVIRONMENT }}"
      - name: Deploy
        run: eval "npx wrangler publish --env ${{ secrets.ENVIRONMENT }}"
