name: CI/CD
on:
  push:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: npm
      - run: npm install
      - uses: ozaytsev86/create-env-file@v1
        with:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_USER_EMAIL: ${{ secrets.FIREBASE_USER_EMAIL }}
          FIREBASE_USER_PASSWORD: ${{ secrets.FIREBASE_USER_PASSWORD }}
          FIREBASE_ADMIN_EMAIL: ${{ secrets.FIREBASE_ADMIN_EMAIL }}
          FIREBASE_ADMIN_PASSWORD: ${{ secrets.FIREBASE_ADMIN_PASSWORD }}
      - run: npm test
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-22.04
  #   name: Deploying
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cloudflare/wrangler-action@2.0.0
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         command: publish --env ${{ vars.ENVIRONMENT }}
