name: Scrape Official Temtem Wiki
on:
  workflow_dispatch:
  repository_dispatch:
    types: [webhook]
  schedule:
    - cron: "0 */12 * * *"
jobs:
  scrape:
    runs-on: ubuntu-22.04
    name: Scraping
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: npm
      - run: npm install
      - run: npm run scrape
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git diff --quiet && git diff --staged --quiet || git commit -am "🤖 Update Temzone database"
          git push origin main
